name: BedrockDialog
version: "${version}"
main: me.f0reach.bedrockdialog.BedrockDialogPlugin
api-version: "1.21"
bootstrapper: me.f0reach.bedrockdialog.BedrockDialogBootstrap
dependencies:
  server:
    Geyser-Spigot:
      required: false
      load: BEFORE
      join-classpath: true
    floodgate:
      required: false
      load: BEFORE
      join-classpath: true

permissions:
  bedrockdialog.dialog.open:
    default: op
  bedrockdialog.dialog.reload:
    default: op
